### ISSUE TITLE
This is no longer needed, update your bios to the latest AGESA

### ISSUE THREAD

**Issue by gnif** [gusmd/pubfix#4]
With the latest AGESA this problem is fixed.

**Comment by atonkyra** [comment]
Still crashes for me with TR1950X / Gigabyte F10 BIOS (AGESA 1.1.0.0) in a VFIO/KVM setup.

**Comment by gnif** [comment]
Works fine for me, I am running the same setup.

**Comment by atonkyra** [comment]
That is fairly weird, then. In any case on my setup I still need to set affinity or the game will crash when loading lobby.

**Comment by atonkyra** [comment]
@gnif How are you running your VM, can you share the CPU related settings? :)

**Comment by gnif** [comment]
I use a custom script to launch qemu directly, pinning CPU threads to cores, etc. Running Qemu 3.0.0rc1

**Comment by atonkyra** [comment]
Hmm, 3.0.0-rc2 here. Are you passing through host-cpu or something else? My setup is similar with regards to pinning etc.

**Comment by gusmd** [comment]
I'm running the latest available BIOS on my MSI x370SLI PLUS with a Ryzen 1700X (AGESA 1.0.0.2a) and still need to set affinity as well.

As laudable as the intention of this issue is, a lot of people still, realistically, need this. 

I could perhaps add a note to the README along the lines of: "try updating your BIOS to the latest version available before resorting to this, as it may fix the problem".

**Comment by gnif** [comment]
AGESA 1.0.0.2a is not the latest version, please ask for an updated BIOS from the manufacturer.

Adding the extra to the README would resolve this issue.

**Comment by gusmd** [comment]
I'm aware it's not the latest version. It is, however, the latest available to users of my motherboard. Hence my point above: the intention of this is laudable, but many people still realistically need this tool. 

I've added a note to the README. Thanks for opening the issue!
